[book]
authors = ["Justin Wayne Liles"]
language = "en"
multilingual = false
src = "src"
title = "SMV Documentation"
description = "Comprehensive documentation for the SMV smart file management tool"

[output.html]
# Repository URL for the "Edit" button
git-repository-url = "https://github.com/jwliles/smv"
edit-url-template = "https://github.com/jwliles/smv/edit/main/docs/{path}"
# Enable search and configure it
search = { enable = true, limit-results = 15, use-boolean-and = true, boost-title = 2, boost-hierarchy = 1, boost-paragraph = 1, expand = true, heading-split-level = 3 }
# Enable copy button for code blocks
copy-fonts = true
# Additional features
mathjax-support = false
no-section-label = false
preferred-dark-theme = "ayu"
additional-css = ["theme/custom.css"]
default-theme = "light"